# Generated by Django 5.2.7 on 2025-12-01 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EcommerceProducts", "0002_browsinghistory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categories",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.AddField(
            model_name="categories",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="EcommerceProducts.categories",
            ),
        ),
    ]
