# Generated by Django 5.2.7 on 2025-12-02 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EcommerceProducts", "0003_alter_categories_options_categories_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="description",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
