# Generated by Django 5.2.7 on 2025-12-04 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("EcommerceProducts", "0004_alter_products_description"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Orders",
        ),
    ]
