# Generated by Django 5.2.7 on 2025-12-04 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce_orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Processing", "Processing"),
                    ("Delivered", "Delivered"),
                    ("Received", "Received"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
